TrueFakers Web Prototipo/Models/Comentario.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace TrueFakers_Web_Prototipo.Models
{
    public class Comentario
    {
        public int Id { get; set; }
        public string Contenido { get; set; }
        public DateTime Timestamp { get; set; }
        public int UsuarioId { get; set; }
        public int NoticiaId { get; set; }
        public Noticia Noticia { get; set; }
    }
}

TrueFakers Web Prototipo/Models/ErrorViewModel.cs
using System;

namespace TrueFakers_Web_Prototipo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TrueFakers Web Prototipo/Models/Multimedia.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace TrueFakers_Web_Prototipo.Models
{
    public class Multimedia
    {
        public int Id { get; set; }
        public string Filepath { get; set; }
        public int NoticiaId { get; set; }
    }
}

TrueFakers Web Prototipo/Models/Noticia.cs
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations.Schema;

namespace TrueFakers_Web_Prototipo.Models
{
    public class Noticia
    {
        public int Id { get; set; }
        public DateTime Fecha { get; set; }
        public int Estado { get; set; } = 1;
        public string Titulo { get; set; }
        public string Cuerpo { get; set; }
        public int Veredicto { get; set; } = 0;
        public int UsuarioId { get; set; }
        public Usuario Usuario { get; set; }
        public ICollection<Comentario> Comentarios { get; set; }
        public ICollection<Multimedia> Multimedias { get; set; }
    }
}

TrueFakers Web Prototipo/Models/Usuario.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace TrueFakers_Web_Prototipo.Models
{
    public class Usuario
    {
        public int Id { get; set; }
        public string Mail { get; set; }
        public string Clave { get; set; }
        public int Rol { get; set; }
        public ICollection<Noticia> Noticias { get; set; }
    }
}

TrueFakers Web Prototipo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TrueFakers_Web_Prototipo.Models;

namespace TrueFakers_Web_Prototipo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TrueFakers Web Prototipo/Controllers/NoticiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace TrueFakers_Web_Prototipo.Controllers
{
    public class NoticiaController : Controller
    {
        public IActionResult LeerNoticia()
        {
            return View();
        }
        public IActionResult ListaNoticias()
        {
            return View();
        }

        public IActionResult CrearNoticia()
        {
            return View();
        }
    }
}

TrueFakers Web Prototipo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "TrueFakers";
}

<div class="text-center">
    <br />
    <h1 class="display-4">Bienvenido a TrueFakers</h1><br />
    <p class="text-justify">
        La plataforma de periodismo etico y libre, cuyo porposito es dar una fuente
        confiable de informacion y en donde todos puedan participar en la verificacion de una noticia
        colaborativamente.
    </p>
    <p class="text-justify">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas vel eros ut quam suscipit pretium. 
        Etiam quam nulla, vestibulum a mi sed, consequat fermentum lacus. Nam libero enim, blandit rhoncus 
        porttitor at, consequat nec leo. Sed sed magna viverra, scelerisque mauris in, porttitor tellus. 
        Sed bibendum orci nisl, id fermentum erat dignissim id. Morbi fermentum sodales purus id aliquam. 
        Vestibulum feugiat rhoncus tincidunt.
        In posuere justo et erat rutrum luctus. Quisque lacinia elit porttitor molestie iaculis. 
        Pellentesque sit amet leo sodales, ullamcorper massa at, hendrerit massa. Phasellus sit amet placerat massa, 
        id tempor lectus. Sed maximus vulputate lectus eu venenatis. Aenean porta velit ut nunc eleifend hendrerit. 
        Aliquam laoreet condimentum lobortis. Maecenas faucibus leo laoreet, laoreet est at, commodo felis. 
        Duis malesuada mollis velit, sed tincidunt dolor porta tempor.
        Integer vitae libero nulla. Sed vel nulla arcu. In consectetur venenatis eros, id cursus arcu fringilla ut. 
        Ut vel volutpat eros. Cras ultricies consectetur ligula, id sagittis enim pulvinar ut. Integer luctus commodo libero 
        eget euismod. Vivamus faucibus non mi eget congue. Ut scelerisque, massa vel malesuada ultrices, metus erat eleifend 
        felis, vel rutrum odio massa a justo. Etiam aliquet molestie lacus, quis maximus orci. Curabitur a dui molestie, condimentum mauris.
    </p>
    <br />
    <div class="grid-container-inicio">
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Deforestacion en la selva Amazonica</h3>
                <h6>Continua la deforestacion en la selva amazonica</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Titulo Noticia 5</h3>
                <h6>Mini Descripcion</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
            </a>
        </div>
    </div>
</div>

TrueFakers Web Prototipo/Views/Noticia/CrearNoticia.cshtml
@model TrueFakers_Web_Prototipo.Models.Noticia

@{
    ViewData["Title"] = "Redactar Noticia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <br />
<h4>Redactar Noticia</h4>
<hr />
<div class="">
    <div class="">
        <form asp-action="CrearNoticia" class="grid-container-create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuerpo" class="control-label">Contenido</label>
                <div class="form-group">
                    <textarea asp-for="Cuerpo" class="form-control" id="" rows="15"></textarea>
                </div>
                <span asp-validation-for="Cuerpo" class="text-danger"></span>
            </div>
            <div class="form-group das">
                <input type="submit" value="Publicar Noticia" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="text-md-right">
    <a asp-action="ListaNoticias">Volver atras</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TrueFakers Web Prototipo/Views/Noticia/LeerNoticia.cshtml
@model TrueFakers_Web_Prototipo.Models.Noticia

@{
    ViewData["Title"] = "LeerNoticia";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div>
    <br />
    <h3>Crazy Cat</h3>
    <h5>Un gato loco se ha escapado del manicomio!</h5>
    <hr />
    <dl class="row">
        <dd class="col-sm-2 text-justify font-weight-lighter">
            Un gato loco se ha escapado del manicomio!, todo lo que tiene que saber, ahora ya en esta noticia.
        </dd>
        <dd class="col-sm-10 text-justify">
            A crazy cat has escaped from an asylum, take cover kids consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
            Ut scelerisque consequat libero, non consectetur turpis mollis id.
            Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
            A crazy cat has escaped from an asylum, take cover kids consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
            Ut scelerisque consequat libero, non consectetur turpis mollis id.
            Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
            A crazy cat has escaped from an asylum, take cover kids consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
            Ut scelerisque consequat libero, non consectetur turpis mollis id.
            Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
        </dd>
        <dd class="col-sm-12 text-justify">
            A crazy cat has escaped from an asylum, take cover kids consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
            Ut scelerisque consequat libero, non consectetur turpis mollis id.
            Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
            A crazy cat has escaped from an asylum, take cover kids consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
            Ut scelerisque consequat libero, non consectetur turpis mollis id.
            Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
        </dd>
    </dl>
    <br />
    <div class="grid-container-votacion text-center">
        <button class="btn btn-outline-danger">falso</button>
        <p class="align">3 / 14</p>
        <button class="btn btn-outline-success">verdadero</button>
    </div>
    <br />
    <hr />
    <div class="grid-container-comentario">
        <h5 class="font-weight-bold">Comentarios</h5>
        <p>Pedro Villa: No creo que esto sea verdad, como un gato loco ... lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet  lorem ipsum dolor sit amet.</p>
        <p>Lalo Lein: Este es un comentario creado por un usuario.</p>
        <p>Elsa pato: No creo que esto sea verdad, como un gato loco ... lorem ipsum dolor sit amet lorem ipsum dolor sit amet lorem ipsum dolor sit amet.</p>
        <div>
            <form asp-action="Comentar" class="grid-container-create">
                <div class="form-group">
                    <textarea class="form-control" id="crear-comentario" rows="2"></textarea>
                </div>
                <div class="form-group">
                    <input type="submit" value="Comentar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
</div>
<br />
<div class="text-md-right">
    <a asp-action="ListaNoticias">Volver atras</a>
</div>

TrueFakers Web Prototipo/Views/Noticia/ListaNoticias.cshtml
@{
    ViewData["Title"] = "Noticias";
    Layout = "_Layout";
}
    <div>
        <br />
        <h1 class="text-center">Noticias</h1>
        <br />
    </div>
    <div class="grid-container">
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Deforestacion en la selva Amazonica</h3>
                <h6>Continua la deforestacion en la selva amazonica</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-success text-right">verdadera</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Tasa Mortalidad Covid19</h3>
                <h6>Un indicador mas seguro para medir la tasa de mortalidad</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-info text-right">no verificado</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Crazy Cat</h3>
                <h6>Crazy cat escaped from asylum</h6>
                <p>
                    A crazy cat has escaped from an asylum, take cover kids consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-success text-right">verdadera</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Titulo Noticia 4</h3>
                <h6>Mini Descripcion</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-danger text-right">falsa</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Titulo Noticia 5</h3>
                <h6>Mini Descripcion</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-info text-right">no verificado</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Titulo Noticia 6</h3>
                <h6>Mini Descripcion</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-warning text-right">impreciso</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Titulo Noticia 7</h3>
                <h6>Mini Descripcion</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-info text-right">no verificado</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Titulo Noticia 8</h3>
                <h6>Mini Descripcion</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-danger text-right">falsa</p>
            </a>
        </div>
        <div class="noticia">
            <a href="#">
                <h3 class="text-center">Titulo Noticia 9</h3>
                <h6>Mini Descripcion</h6>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin porta ac ex fermentum tincidunt.
                    Ut scelerisque consequat libero, non consectetur turpis mollis id.
                    Nunc mi quam, suscipit vel vestibulum nec, varius in velit.
                </p>
                <hr />
                <p class="text-warning text-right">impreciso</p>
            </a>
        </div>

    </div>

TrueFakers Web Prototipo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TrueFakers_Web_Prototipo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/noticia.css" />
    <link rel="stylesheet" href="~/css/comentario.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TrueFakers</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Noticia" asp-action="ListaNoticias">Noticias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Noticia" asp-action="LeerNoticia">LeerNoticia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Noticia" asp-action="CrearNoticia">CrearNoticia</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TrueFakers_Web_Prototipo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>