TrueFakers/TrueFakers-ale/Models/Noticia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TrueFakers_ale.Models
{
    public class Noticia
    {
        public int NoticiaId { get; set; }
        public DateTime Fecha { get; set; }
        public int Estado { get; set; }
        public string Titulo { get; set; }
        public string SubTitulo { get; set; }
        public string Cuerpo { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsVerified { get; set; }
        public int Veredicto { get; set; } = 0;
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Comentario> Comentarios { get; set; }
        public virtual ICollection<Voto> Votos { get; set; }
    }
}

TrueFakers/TrueFakers-ale/Controllers/NoticiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrueFakers_ale.Data;
using TrueFakers_ale.Models;

namespace TrueFakers_ale.Controllers
{
    [Authorize]
    public class NoticiaController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<Usuario> userManager;
        private readonly SignInManager<Usuario> signManager;

        public NoticiaController(ApplicationDbContext context, UserManager<Usuario> userManager, SignInManager<Usuario> signManager)
        {
            _context = context;
            this.userManager = userManager;
            this.signManager = signManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            IEnumerable<Noticia> noticias = await GetNoticiasByEnabled(true);
            return View(noticias);
        }

        [HttpGet]
        public async Task<IActionResult> NoAprobadas()
        {
            IEnumerable<Noticia> noticias = await GetNoticiasByEnabled(false);
            return View("Index", noticias);
        }

        [HttpGet]
        public async Task<IActionResult> Falsas()
        {
            List<Noticia> noticias = await GetNoticiasByVeredicto(false);
            return View("Index", noticias);
        }

        [HttpGet]
        public async Task<IActionResult> Verdaderas()
        {
            List<Noticia> noticias = await GetNoticiasByVeredicto(true);
            return View("Index", noticias);
        }

        [HttpGet]
        public async Task<IActionResult> Imprecisas()
        {
            List<Noticia> noticias = await GetNoticiasByVeredicto();
            return View("Index", noticias);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Noticia model)
        {
            if (ModelState.IsValid)
            {
                var currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                Noticia noticia = new Noticia
                {
                    Titulo = model.Titulo,
                    SubTitulo = model.SubTitulo,
                    Cuerpo = model.Cuerpo,
                    Fecha = DateTime.Now,
                    IsEnabled = false,
                    IsVerified = false,
                    Estado = 0,
                    Veredicto = 0,
                    Usuario = await GetUserById(currentUserId)
                };

                _context.Noticia.Add(noticia);
                int result = await _context.SaveChangesAsync();

                if (result != 0)
                {
                    return RedirectToAction("index", "home");
                }
                else
                {
                    return NoContent();
                }
            }

            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Noticia noticia = await GetNoticia(id);
            List<Comentario> comentarios = await GetComentarios(noticia);

            if (noticia == null)
            {
                return NotFound();
            }

            ViewData["HavePermission"] = false;

            if (signManager.IsSignedIn(User))
            {
                string currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                if (User.IsInRole("editor") || User.IsInRole("admin") || (currentUserId.Equals(noticia.Usuario.Id)))
                {
                    ViewData["HavePermission"] = true;
                }
            }

            ViewData["CommentsList"] = comentarios;
            return View(noticia);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var noticia = await _context.Noticia.FindAsync(id);
            if (noticia == null)
            {
                return NotFound();
            }
            return View(noticia);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Noticia model)
        {
            if (id == model.NoticiaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Noticia noticia = await _context.Noticia.FindAsync(id);
                noticia.Titulo = model.Titulo;
                noticia.SubTitulo = model.SubTitulo;
                noticia.Cuerpo = model.Cuerpo;
                noticia.IsEnabled = model.IsEnabled;
                noticia.Veredicto = model.Veredicto;
                noticia.Estado = model.Estado;

                if(model.Veredicto != 0)
                {
                    noticia.IsVerified = true;
                }
                else
                {
                    noticia.IsVerified = false;
                }

                if(!noticia.IsVerified)
                {
                    noticia.Veredicto = 0;
                }

                try
                {
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    throw;
                }
                return RedirectToAction("index", "home");
            }
            return View(model);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Search(string query)
        {
            ViewData["SearchNoticia"] = query;

            var searchQuery = from x in _context.Noticia select x;
            if (!String.IsNullOrEmpty(query))
            {
                if (User.IsInRole("editor") || User.IsInRole("admin") || User.IsInRole("usuario"))
                {
                    searchQuery = searchQuery.Where(x => x.Titulo.Contains(query));
                } 
                else
                {
                    searchQuery = searchQuery.Where(x => x.Titulo.Contains(query) && x.Veredicto == 2 && x.IsVerified == true);
                }
                
            }
            return View(await searchQuery.AsNoTracking().ToListAsync());
        }

        [HttpGet]
        public async Task<IActionResult> ListVeredictos()
        {
            //IList<string> roleOfRandomUser = new List<string>();

            //while (!roleOfRandomUser.Contains("editor"))
            //{
            //    Random rnd = new Random();

            //    List<Usuario> allUsers = await userManager.Users.ToListAsync();
            //    List<Usuario> shuffleUsers = allUsers.OrderBy(x => rnd.Next()).ToList();

            //    Usuario randomUser = shuffleUsers.Take(1).First();
            //    roleOfRandomUser = await userManager.GetRolesAsync(randomUser);

            //    if (roleOfRandomUser.Contains("editor"))
            //    {
            //        ViewData["randomEditor"] = randomUser.Id;
            //    }
            //}

            List<Noticia> noticias = await _context.Noticia.Where(n => n.Estado == 1).ToListAsync();

            return View(noticias);
        }


        //[HttpPost]
        //public async Task<IActionResult> Veredicto(int noticiaId, Noticia model)
        //{
        //    Noticia copyNoticia = await GetNoticia(noticiaId);

        //    if (ModelState.IsValid)
        //    {
        //        copyNoticia.Veredicto = model.Veredicto;
        //        RedirectToAction("", "");
        //    }

        //    return View(copyNoticia);
        //}


        public async Task<Usuario> GetUserById(string currentUserId)
        {
            Usuario user = await userManager.FindByIdAsync(currentUserId);
            return user;
        }

        public async Task<List<Comentario>> GetComentarios(Noticia id)
        {
            List<Comentario> comentarios = await _context.Comentario.Include(c => c.Usuario).Where(c => c.Noticia == id).ToListAsync();
            return comentarios;
        }

        public async Task<Noticia> GetNoticia(int? id)
        {
            Noticia noticia = await _context.Noticia.Include(n => n.Usuario).Include(n => n.Comentarios).FirstOrDefaultAsync(m => m.NoticiaId == id);
            return noticia;
        }

        public async Task<List<Noticia>> GetNoticiasByVeredicto(bool veredicto)
        {
            return await GetNoticiasByVeredicto(veredicto, false);
        }

        public async Task<IEnumerable<Noticia>> GetNoticiasByEnabled(bool enabledNews)
        {
            // Este metodo retorna una lista de noticias segun si estan aceptadas o no para ser verificadas
            IEnumerable<Noticia> _noticias = await _context.Noticia.Where(n => (n.IsEnabled == enabledNews && n.IsVerified == false)).ToListAsync();
            return _noticias;
        }

        public async Task<List<Noticia>> GetNoticiasByVeredicto(bool veredicto = true, bool imprecisa = true)
        {
            // Este metodo retorna uan lista de noticia segun su veredicto, por defecto retorna las noticias imprecisas 
            List<Noticia> noticias = null;

            if(veredicto && !imprecisa)
            {
                noticias = await _context.Noticia.Where(n => n.Veredicto == 2 && (n.IsEnabled == true && n.IsVerified == true)).ToListAsync();
            }
            else if(!veredicto && !imprecisa)
            {
                noticias = await _context.Noticia.Where(n => n.Veredicto == 1 && (n.IsEnabled == true && n.IsVerified == true)).ToListAsync();
            }

TrueFakers/TrueFakers-ale/Controllers/VotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TrueFakers_ale.Data;
using TrueFakers_ale.Models;

namespace TrueFakers_ale.Controllers
{
    public class VotoController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<Usuario> userManager;

        public VotoController(ApplicationDbContext context, UserManager<Usuario> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }

        public async Task<IActionResult> VotarVerdadera(int id)
        {
            bool flag = await CrearVoto(2, id);

            if(flag)
            {
                return RedirectToAction("Details", "Noticia", new { Id = id });
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> VotarFalsa(int id)
        {
            bool flag = await CrearVoto(1, id);

            if (flag)
            {
                return RedirectToAction("Details", "Noticia", new { Id = id });
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<IActionResult> VotarImprecisa(int id)
        {
            bool flag = await CrearVoto(3, id);

            if (flag)
            {
                return RedirectToAction("Details", "Noticia", new { Id = id });
            }
            else
            {
                return NotFound();
            }
        }

        public async Task<bool> CrearVoto(int veredicto, int idNoticia)
        {
            string currentUserId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            Usuario usuario = await GetUserById(currentUserId);
            Noticia noticia = await GetNoticia(idNoticia);
            Voto voto = _context.Voto.Where(v => v.Usuario == usuario && v.Noticia == noticia).FirstOrDefault();
            int result = 0;
            
            if(voto != null)
            {
                voto.Tipo = veredicto;
            }
            else
            {
                voto = new Voto();
                voto.Tipo = veredicto;
                voto.Noticia = noticia;
                voto.Usuario = usuario;
                _context.Voto.Add(voto);
            }

            result = await _context.SaveChangesAsync();

            if (result != 0)
                return true;
            else
                return false;
            
        }

        public async Task<Noticia> GetNoticia(int? id)
        {
            Noticia noticia = await _context.Noticia.Include(n => n.Usuario).Include(n => n.Comentarios).FirstOrDefaultAsync(m => m.NoticiaId == id);
            return noticia;
        }

        public async Task<Usuario> GetUserById(string currentUserId)
        {
            Usuario user = await userManager.FindByIdAsync(currentUserId);
            return user;
        }
    }
}

TrueFakers/TrueFakers-ale/Views/Noticia/Create.cshtml
@model Noticia

@{
    ViewData["Title"] = "Create";
}


<div class="row justify-content-center">
    <div class="col-md-4">
        <h1 class="mt-3 mb-5 text-center">Crea tu noticia</h1>

        <h4 class="mt-5 mb-3">Noticia</h4>
        <hr />
        <form class="mt-5" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubTitulo" class="control-label"></label>
                <input asp-for="SubTitulo" class="form-control" />
                <span asp-validation-for="SubTitulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuerpo" class="control-label"></label>
                <textarea asp-for="Cuerpo" class="form-control" rows="15"></textarea>
                <span asp-validation-for="Cuerpo" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Enviar!</button>
        </form>
    </div>
</div>

TrueFakers/TrueFakers-ale/Views/Noticia/Details.cshtml
@model Noticia
@inject UserManager<Usuario> userManager;
@inject SignInManager<Usuario> signInManager;
@{
    ViewData["Title"] = "Details";
}

@{
    int veredicto = Model.Veredicto;
    string veredictoForView;
    string color;

    if (veredicto == 0)
    {
        veredictoForView = "Pendiente";
        color = "#a5743f";
    }
    else if (veredicto == 1)
    {
        veredictoForView = "Falso";
        color = "red";
    }
    else if (veredicto == 2)
    {
        veredictoForView = "Verdadero";
        color = "green";
    }
    else
    {
        veredictoForView = "Impreciso";
        color = "orange";
    }

    var havePermission = ViewData["HavePermission"];
    var comentarios = ViewData["CommentsList"] as List<Comentario>;
}

<div class="container mt-5">
    <div class="jumbotron mb-5" style="background: #F6F5E4">
        <div class="row">
            <div class="col text-center">
                <h1 class="display-4 mb-5">@Model.Titulo</h1>
                <p class="lead mt-1">@Model.SubTitulo</p>
            </div>
        </div>
        <hr class="my-4" />
        <div class="row">
            <div class="col">
                <p>@Model.Cuerpo</p>
            </div>
        </div>
        <hr class="my-4" />
        <div class="row">
            <div class="col">
                <h3 class="" style="color: @color;">@veredictoForView</h3>
            </div>
            @if (Model.IsEnabled)
            {
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a id="verdadera" class="btn btn-success" style="color: white" asp-controller="Voto" asp-action="VotarVerdadera" asp-route-id="@Model.NoticiaId">Verdadera</a>
                    <a id="falsa" class="btn btn-danger" style="color: white" asp-controller="Voto" asp-action="VotarFalsa" asp-route-id="@Model.NoticiaId">Falsa</a>
                    <a id="impreciso" class="btn btn-warning" style="color: white" asp-controller="Voto" asp-action="VotarImprecisa" asp-route-id="@Model.NoticiaId">Imprecisa</a>
                </div>
            }

            @if (havePermission.Equals(true))
            {
                    <div class="col text-right">
                        <div class="d-flex justify-content-end">
                            <a class="btn btn-light" asp-action="Edit" asp-route-id="@Model.NoticiaId">Editar</a>
                        </div>
                    </div>
            }
        </div>

    </div>
    <div class="row">
        <div class="col text-right">
            @if (User.Identity.IsAuthenticated)
            {
                if (Model.Veredicto == 0)
                {
                    <a class="btn btn-light" asp-controller="Noticia" asp-action="Index">Volver Atras</a>
                }
                else if (Model.Veredicto == 2)
                {
                    <a class="btn btn-light" asp-controller="Noticia" asp-action="Verdaderas">Volver Atras</a>
                }
                else if (Model.Veredicto == 3)
                {
                    <a class="btn btn-light" asp-controller="Noticia" asp-action="Imprecisas">Volver Atras</a>
                }
                else
                {
                    <a class="btn btn-light" asp-controller="Noticia" asp-action="Falsas">Volver Atras</a>
                }
            }
            else
            {
                <a class="btn btn-light" asp-controller="Home" asp-action="Index">Volver Atras</a>
            }
        </div>
    </div>

    <div class="jumbotron mt-4" style="background: #F6F5E4">
        @if (comentarios.Count != 0)
        {
            @foreach (var comentario in comentarios)
            {
                <div class="row mb-2 justify-content-center">
                    <div class="col-6 text-center d-flex align-content-center">
                        <div class="card rounded" style="width: 60vw;">

                            <div class="card-header" style="background: #E7DDB6">
                                @comentario.Usuario.Email
                            </div>
                            <div class="card-body bg-white" style="background: #ECE6C6">
                                <p>@comentario.Contenido</p>
                                <a class="btn btn-danger mt-4" asp-controller="Comentario" asp-action="Report" asp-route-id="@comentario.ComentarioId" style="color: white">Reportar</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h6>No hay cometarios</h6>
        }
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form class="mt-4 mb-4" method="post" asp-controller="Comentario" asp-action="Comentar" asp-route-noticiaId="@Model.NoticiaId">
                    <div class="form-group">
                        <textarea class="form-control" rows="6" name="nuevoComentario" style="resize: none;" maxlength="998"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary text-center">Comenta!</button>
                </form>
            </div>
        </div>
    }
</div>

TrueFakers/TrueFakers-ale/Views/Noticia/Edit.cshtml
@model Noticia
@{
    ViewData["Title"] = "Edit";
}

@{
    int veredicto = Model.Veredicto;
    string veredictoForView;

    if (veredicto == 0)
    {
        veredictoForView = "Pendiente";
    }
    else if (veredicto == 1)
    {
        veredictoForView = "Falso";
    }
    else if (veredicto == 2)
    {
        veredictoForView = "Verdadero";
    }
    else
    {
        veredictoForView = "Impreciso";
    }
}

<div class="row justify-content-center">
    <div class="col-md-6">
        <h1 class="mt-5 mb-5"> Editar Noticia </h1>
        <form method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo"></label>
                <input asp-for="Titulo" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="SubTitulo"></label>
                <input asp-for="SubTitulo" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Cuerpo" class="control-label"></label>
                <textarea asp-for="Cuerpo" class="form-control" rows="10"></textarea>
                <span asp-validation-for="Cuerpo" class="text-danger"></span>
            </div>
            @if (User.IsInRole("admin") || User.IsInRole("editor"))
            {
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" id="IsEnabled" asp-for="IsEnabled">
                    <label class="custom-control-label" for="IsEnabled">Habilitar Noticia</label>
                </div>
                @*
                    <div class="custom-control custom-checkbox">
                        <input type="checkbox" class="custom-control-input" id="IsVerified" asp-for="IsVerified">
                        <label class="custom-control-label" for="IsVerified">@Html.DisplayNameFor(model => model.IsVerified)</label>
                    </div>
                *@
                <br />
                <div class="form-group d-inline-flex ">
                    <label for="select-veredicto" class="align-self-center mt-2 mr-2">Veredicto</label>
                    <select id="select-veredicto" asp-for="Veredicto" class="form-control" style="width:200px;">
                        <option value="0">Pendiente</option>
                        <option value="1">Falso</option>
                        <option value="2">Verdadero</option>
                        <option value="3">Impreciso</option>
                    </select>
                    <span asp-validation-for="Veredicto" class="text-danger"></span>
                </div>
            }
            <hr />
            <button type="submit" class="btn btn-primary">Editar</button>
        </form>
        <div class="row">
            <div class="col text-right">
                @if (User.Identity.IsAuthenticated)
                {
                    if (Model.Veredicto == 0)
                    {
                        <a class="btn btn-light" asp-controller="Noticia" asp-action="Index">Volver Atras</a>
                    }
                    else if (Model.Veredicto == 2)
                    {
                        <a class="btn btn-light" asp-controller="Noticia" asp-action="Verdaderas">Volver Atras</a>
                    }
                    else if (Model.Veredicto == 3)
                    {
                        <a class="btn btn-light" asp-controller="Noticia" asp-action="Imprecisas">Volver Atras</a>
                    }
                    else
                    {
                        <a class="btn btn-light" asp-controller="Noticia" asp-action="Falsas">Volver Atras</a>
                    }
                }
                else
                {
                    <a class="btn btn-light" asp-controller="Home" asp-action="Index">Volver Atras</a>
                }
            </div>
        </div>
    </div>
</div>

TrueFakers/TrueFakers-ale/Views/Noticia/Index.cshtml
@model IEnumerable<Noticia>

@{
    ViewData["Title"] = "Noticias general";
}

<div class="container">
    <div class="text-center mb-5 mt-5">
        <h1 class="display-4">TrueFakers</h1>
    </div>
    <div class="container-flex">
        @foreach (var item in Model)
        {
            <div class="box">
                <partial name="~/Views/Noticia/Noticia.cshtml" model='item' />
            </div>
        }
    </div>
</div>

TrueFakers/TrueFakers-ale/Views/Noticia/ListVeredictos.cshtml
@model IEnumerable<Noticia>

@{
    ViewData["Title"] = "Lista veredictos";
}

<div class="container mt-5">
    <div class="text-center mb-5">
        <h1 class="display-4">Veredictos por revisar</h1>
    </div>
        @foreach (var item in Model)
        {
            <div>
                <partial name="~/Views/Noticia/Veredicto.cshtml" model='item' />
            </div>
        }
</div>

TrueFakers/TrueFakers-ale/Views/Noticia/Noticia.cshtml
@model Noticia

@{
    ViewData["Title"] = "Index";
}

@{
    var tmpContenido = Model.Cuerpo;
    if (tmpContenido.Length >= 200)
        tmpContenido = tmpContenido.Substring(0, 200);
    else
        tmpContenido = tmpContenido.Substring(0, tmpContenido.Length);
}

@{
    int veredicto = Model.Veredicto;
    string veredictoForView;
    string color;

    if (veredicto == 0)
    {
        veredictoForView = "Pendiente";
        color = "#a5743f";
    }
    else if (veredicto == 1)
    {
        veredictoForView = "Falso";
        color = "red";
    }
    else if(veredicto == 2)
    {
        veredictoForView = "Verdadero";
        color = "green";
    }
    else
    {
        veredictoForView = "Impreciso";
        color = "orange";
    }
}





<a title="Leer noticia completa" style="text-decoration: none; color: inherit" asp-controller="Noticia" asp-action="Details" asp-route-id="@Model.NoticiaId">
    <div class="card" style="min-height: 450px">
        <div class="card-header" style="background: #E7DDB6; max-height:inherit">
            <h4>@Model.Titulo</h4>
        </div>
        <div class="card-body" style="background: #F6F5E4">
            <h5 class="card-title">@Model.SubTitulo</h5>
            <p class="card-text">@tmpContenido . . .</p>
        </div>
        <div style="background: #E7DDB6; color: @color;" class="card-footer">
            @veredictoForView
        </div>
    </div>
</a>

TrueFakers/TrueFakers-ale/Views/Noticia/Search.cshtml
@model IEnumerable<Noticia>

    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4 mb-4 mt-5">
                    <partial name="~/Views/Noticia/Noticia.cshtml" model='item' />
                </div>
            }
        </div>
    </div>

TrueFakers/TrueFakers-ale/Views/Noticia/Veredicto.cshtml
@model Noticia

@{
    ViewData["Title"] = "Veredicto";
}

@{
    int veredicto = Model.Veredicto;
    string veredictoForView;

    if (veredicto == 0)
    {
        veredictoForView = "Pendiente";
    }
    else if (veredicto == 1)
    {
        veredictoForView = "Falso";
    }
    else if (veredicto == 2)
    {
        veredictoForView = "Verdadero";
    }
    else
    {
        veredictoForView = "Impreciso";
    }
}

<div class="list-group mb-4">
    <a href="#" class="list-group-item list-group-item-action" style="background-color: lightgray">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">@Model.Titulo</h5>
            <small>@veredictoForView</small>
        </div>
        <p class="mb-1">@Model.SubTitulo</p>
        <small>@Model.Fecha</small>
    </a>
</div>